### ISSUE TITLE
Add label to MR 

### ISSUE THREAD

**Issue by anmir** [novotnyr/gitlab-quickmr-idea-plugin#14]
We have a lot of MR for different types of projects. Usually, we separate them using labels (ui, backend, front...) It will be quite useful to set labels and default labels

**Comment by novotnyr** [comment]
@anmir Can you elaborate where do you want to specify labels?

I can imagine definining a default set of labels in the Preferences).

Confirmation dialog might allow you to customize labels on the particular Merge Request.

**Comment by novotnyr** [comment]
Available in v13.
