### ISSUE TITLE
Can't create a merge request in private repo

### ISSUE THREAD

**Issue by dzastinas** [novotnyr/gitlab-quickmr-idea-plugin#24]
Thanks for a great plugin.

I get the error when creating a merge request:

```Merge Request Failed: Failed to create merge request: GitLab project 'gitlab.com/<PRIVATE REPO>' not found. Do GitLab URL and Git remote match?```

I created a token with api, read_user, read_repository.
My project is in global git lab
Set URL https://gitlab.com/api/v4

git remote -v prints correct git URL. It matches the one in error.

I can connect successfully in settings with a token
![image](https://user-images.githubusercontent.com/13061345/73831205-98e35a00-480e-11ea-8e25-9d4be25deb97.png)

**Comment by novotnyr** [comment]
@dzastinas 

- Do you have multiple origins by any chance?
- How does your `git remote -v` look like? On my test project, connected with private GitLab.com repo, shows:
```
origin  git@gitlab.com:novotnyr/dummy-project.git (fetch)
origin  git@gitlab.com:novotnyr/dummy-project.git (push)
```
The project ID is `novotnyr/dummy-project`, which is used to reach GitLab API.

On your side, it looks like that your project ID is `gitlab.com/<PRIVATE REPO>`, which is strange. The `gitlab.com` prefix does not look right to me.

**Comment by dzastinas** [comment]
- I had multiply, but right now is single

sd

I am using HTTPS URL with credential helper. Maybe here is the issue. Will check with SSH later.

**Comment by novotnyr** [comment]
This might be an issue with HTTP based URLs. I will investigate.
On 7 Feb 2020, 13:40 +0100, dzastinas <notifications@github.com>, wrote:

  *   I had multiply, but right now is single

sd

I am using HTTPS URL with credential helper. Maybe here is the issue. Will check with SSH later.

**Comment by novotnyr** [comment]
I need to investigate the handling of HTTP based origins.

**Comment by novotnyr** [comment]
@dzastinas this is linked to #26

**Comment by novotnyr** [comment]
Resolved in [Release 16](https://github.com/novotnyr/gitlab-quickmr-idea-plugin/releases/tag/v16)
