### ISSUE TITLE
Add template placeholder to add branch name to default merge request title

### ISSUE THREAD

**Issue by novotnyr** [novotnyr/gitlab-quickmr-idea-plugin#3]
Add source branch name placeholder to default merge request title.

See:
https://plugins.jetbrains.com/plugin/11149-gitlab-quick-merge-request#comment=30837

**Comment by Lagoshny** [comment]
Thanks for the issue, also I think that will be good to add to plugin settings **checkbox** which will ask title message when merge request is created.

For example: 
If checkbox has value **true** then when you click to create merge request will show popup window to ask title request message.
if checkbox has value **false** then when you click to create merge request popup window cannot show and use default title message.

**Comment by novotnyr** [comment]
Added to v7.

**Comment by Lagoshny** [comment]
Thanks! It works great!
