### ISSUE TITLE
No plugin items in VCS>Git menu

### ISSUE THREAD

**Issue by kool79** [novotnyr/gitlab-quickmr-idea-plugin#32]
I've filled all plugin paremeters and checked connection to my gitlab server. But I  still dont see any item "Quick Merge request" in menu.
![Screenshot - 11 08 2020 , 02_33_35](https://user-images.githubusercontent.com/4625317/89842749-44cf7e80-db7f-11ea-9d2a-3297640beff0.png)

Idea: Ultimate, v2020.2 (latest ate the moment)

**Comment by novotnyr** [comment]
This might happen when assignees are disabled, and _Enable Quick Merge Request to Favourite Assignee_ is disabled as well.
