### ISSUE TITLE
Add setting to allow confirmation window before create merge request

### ISSUE THREAD

**Issue by Lagoshny** [novotnyr/gitlab-quickmr-idea-plugin#4]
It will be good to add to plugin settings checkbox for allow confirmation window before create merge request.
For example: when create merge request using a shortcut key you can have mistake when push this shortcut key randomly and request will create mistakenly. Therefore to prevent this behavor you can use this checkbox in plugin settings.

**Comment by novotnyr** [comment]
Added to v7.

**Comment by Lagoshny** [comment]
Thanks! It is perfect! But I think need to allow edit title message in confirmation window.

**Comment by novotnyr** [comment]
Editable dialog is a separate issue #5.
