### ISSUE TITLE
Not working with 2021.1

### ISSUE THREAD

**Issue by mirelon** [novotnyr/gitlab-quickmr-idea-plugin#40]
There is no option in menu (see also https://plugins.jetbrains.com/plugin/11149-gitlab-quick-merge-request/reviews#review=52166)

**Comment by novotnyr** [comment]
Unfortunately, I cannot reproduce on IntelliJ 2021.1 / MacOS

Please verify:
- Menu is visible in the context menu of the project directory
- Plugin is properly configured in IntelliJ IDEA Preferences

## Is this plugin available in the context menu?

<img width="729" alt="image" src="https://user-images.githubusercontent.com/1109928/114319714-eb0ac400-9b12-11eb-9cd4-b6b1268ae879.png">

## Is this plugin properly configured in IntelliJ IDEA Preferences?

<img width="434" alt="image" src="https://user-images.githubusercontent.com/1109928/114319738-11306400-9b13-11eb-8896-d87eb85cb059.png">

**Comment by mirelon** [comment]
Solved. It is there.
(I tried to find it in the "Git" menu in the top bar)
![image](https://user-images.githubusercontent.com/1101497/114349116-c2f98000-9b67-11eb-919d-458841c3f4ee.png)
