### ISSUE TITLE
Merge Request #null create

### ISSUE THREAD

**Issue by apexglory** [novotnyr/gitlab-quickmr-idea-plugin#46]
after created mr ,it shows
![image](https://user-images.githubusercontent.com/18387964/142969692-25890bb2-9b7d-42c2-b11c-657b418e2580.png)
then click 'view in gitlab' will throw error
![image](https://user-images.githubusercontent.com/18387964/142969747-ee47375f-c2d1-4242-a11e-c2d24d71bf91.png)
![image](https://user-images.githubusercontent.com/18387964/142969754-a38cda41-0917-401a-b3f1-a989325e14e1.png)
my git remote's url is same with preference settings
![image](https://user-images.githubusercontent.com/18387964/142969829-f7a6a87c-e4f8-4e5b-a7db-c5329e76eafb.png)
![image](https://user-images.githubusercontent.com/18387964/142969856-373d48e9-73d1-45fa-a26f-8bdce2652904.png)
is there any problem with gitlab api?

**Comment by apexglory** [comment]
My webstrom version is 2021.1.3

**Comment by novotnyr** [comment]
Fixed in b7d927db64028a33e6fe98b0de73f843b9e57eef.
