### ISSUE TITLE
Error: Failed to create merge request: Cannot invoke "String.length()" because "s" is null

### ISSUE THREAD

**Issue by hirnschmalz** [novotnyr/gitlab-quickmr-idea-plugin#52]
Everytime I try to create a MR I get the error message

```
Failed to create merge request: Cannot invoke "String.length()" because "s" is null
```

If I can provide more information please let me know.

**Comment by jbureau-qc** [comment]
I am also getting this error on a one computer but not the other one which is quite confusing.

**Comment by novotnyr** [comment]
Duplicate of #51.
