### ISSUE TITLE
Incorrect projectId is used in requests.

### ISSUE THREAD

**Issue by kool79** [novotnyr/gitlab-quickmr-idea-plugin#58]
When I check connection settings in configuration dialog I have seccess message.
When I try to create PR, I see AccessDenied messege. (see screenshot
![scr_2023_04_11T01_22_16](https://user-images.githubusercontent.com/4625317/231021948-fd38ca36-69a0-46eb-b8c2-202985942496.png)
)

I tried to use private token with "api" permissions and with all possible permittions but have the same result.

When I analyzed traffic by Fiddler I found that plugin creates request to
`POST /api/v4/projects/MyGroup%2FMyFolder%2FMyRepo/merge_requests`
where MyGroup, MyFolder and MyRepo - the group name, folder name and repository name.
The header "Private-Token" exists and contains valid value.
Please note on the **_"MyGroup%2FMyFolder%2FMyRepo"_** in  request url
As I understand by gitlab api and by response from "GET /api/v4/projects",   the projects should be rerfenced by numeric id. But instead I see url-encoded path to repo.  Seems it is obtained here: 
com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAction#getProjectName
and not converted to numerical projectId. 

GitLab Community Edition [15.9.4]

**Comment by novotnyr** [comment]
GitLab API supports both numeric IDs and URL-encoded project IDs (`MyGroup%2FMyFolder%2FMyRepo`).

The _Test Connection_ button is not even using the project ID, as it is executing GET requests against `/version` endpoint.

If this _Test Connection_  fails with access denied, please make sure that you are using a proper _Personal Access Token_ and that such token is not expired.

Alternatively, you may try the low-level verification via header:

```
curl -v "https://gitlab.com/api/v4/version" -H "Private-Token: glpat-AAAAAA"
```

**Comment by novotnyr** [comment]
Issue closed due to inactivity.
