### ISSUE TITLE
Gitlab Access Denied issue

### ISSUE THREAD

**Issue by redwert** [novotnyr/gitlab-quickmr-idea-plugin#59]
Sometimes I am getting the next error:
Gitlab Access Denied. Please check Access Token in Preferences.

Yesterday I regenerated the access token without an expiration period. Everything was fine until the restart of the system and the next lunch of PhpShtorm.
After entering the same token to the plugin configuration everything works fine. So the problem is storing access tokens in the plugin configuration.
This is not the first time I have faced this issue -  it could be different time periods plugin works correctly. Previously it was during one month, before that something about 10 days.

**Comment by novotnyr** [comment]
@redwert: which OS are you using (Windows? Mac? Linux?)
What is the status of the _Appearance & Behaviour > System Settings > Password_?

This plugin delegates settings to IntelliJ Platform password management.

**Comment by novotnyr** [comment]
Issue closed due to inactivity.

**Comment by redwert** [comment]
os is Kununtu 23.04

**Comment by novotnyr** [comment]
What is the status of the Appearance & Behaviour > System Settings > Password?
